import os
import re
import json
import ast
from typing import TypedDict, List, Dict, Any

from langgraph.graph import StateGraph, END
from google import genai
from google.genai import types
from dotenv import load_dotenv

# Load env variables from backend/.env
load_dotenv("backend/.env")

# Configure Gemini via the new SDK
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY", ""))
MODEL_NAME = "gemini-2.5-flash"

# ---------------------------------------------------------
# State Definition
# ---------------------------------------------------------
class OrchestratorState(TypedDict):
    issue_title: str
    issue_body: str
    issue_labels: List[str]
    
    # Selected by Ingestion Node
    target_agent: str 
    
    # Retrieved by Context Node
    agent_rules: str
    context_files: Dict[str, str]
    
    # Generated by Execution Node
    proposed_files: Dict[str, str]
    
    # Verification Node
    verification_passed: bool
    verification_feedback: str
    retry_count: int

# ---------------------------------------------------------
# Nodes
# ---------------------------------------------------------

def ingestion_node(state: OrchestratorState) -> OrchestratorState:
    """Ingests the GitHub issue and decides which specialist agent to use."""
    print(f"\n--- [Node: Ingestion] Parsing Issue: {state.get('issue_title')} ---")
    
    prompt = f"""
    You are an Orchestrator Agent. Your job is to read a GitHub issue and assign it to the correct specialist agent.
    
    Available Agents:
    - ai-saas-engineer: Architecture, planning, feature blueprints
    - supabase-schema: Postgres DB, SQL migrations, RLS policies
    - code-critic: Python/TypeScript linting, error handling, testing
    - design-critic: UI/UX, Tailwind, visual aesthetics
    - llm-fallback: AI integrations, prompt engineering, RAG pipelines
    
    Issue Title: {state.get('issue_title')}
    Issue Body: {state.get('issue_body')}
    Labels: {state.get('issue_labels')}
    """
    
    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0,
                response_schema={"type": "OBJECT", "properties": {"target_agent": {"type": "STRING"}}}
            )
        )
        data = json.loads(response.text)
        target_agent = data.get("target_agent", "code-critic")
    except Exception as e:
        print(f"Warning: Ingestion failed via LLM ({e}), defaulting to code-critic")
        target_agent = "code-critic"
        
    print(f"--> Assigned to: {target_agent}")
    return {"target_agent": target_agent}


def context_node(state: OrchestratorState) -> OrchestratorState:
    """Loads the SKILL.md rules for the chosen agent and relevant files."""
    agent = state.get("target_agent", "code-critic")
    print(f"\n--- [Node: Context] Loading rules for {agent} ---")
    
    rules = ""
    # Load global rules
    try:
        with open(".agents/rules/wraft.md", "r", encoding="utf-8") as f:
            rules += "GLOBAL RULES:\n" + f.read() + "\n\n"
    except Exception: 
        pass
    
    # Load specific agent skill
    try:
        with open(f".agents/skills/{agent}/SKILL.md", "r", encoding="utf-8") as f:
            rules += f"AGENT RULES:\n" + f.read()
    except Exception: 
        pass
        
    # Extract file paths from issue body (e.g. `backend/services/rag.py`)
    files = {}
    paths = re.findall(r'`([a-zA-Z0-9_\-\./\\]+\.[a-zA-Z0-9]+)`', state.get("issue_body", ""))
    
    for path in paths:
        try:
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8") as f:
                    files[path] = f.read()
        except Exception: 
            pass
            
    print(f"--> Loaded Context Files: {list(files.keys())}")
    return {"agent_rules": rules, "context_files": files}


def execution_node(state: OrchestratorState) -> OrchestratorState:
    """The specialist agent writes the code fix."""
    print("\n--- [Node: Execution] Generating fix ---")
    
    context_str = "\n".join([f"FILE {k}:\n```\n{v}\n```\n" for k, v in state.get("context_files", {}).items()])
    
    prompt = f"""
    You are the specialized AI agent: {state.get('target_agent')}
    
    RULES TO FOLLOW:
    {state.get('agent_rules')}
    
    CURRENT ISSUE:
    {state.get('issue_title')}
    {state.get('issue_body')}
    
    CONTEXT FILES PROVIDED:
    {context_str}
    
    FEEDBACK FROM PREVIOUS VERIFICATION (if any):
    {state.get('verification_feedback', 'None')}
    
    Based on the issue and rules, provide the fully updated code for the files that need changing.
    Respond with a JSON object where the keys are the file paths, and the values are the COMPLETE new code contents.
    Example: {{"backend/services/rag.py": "import os\\n..."}}
    """
    
    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.2, # Slight temp for creative problem solving
            )
        )
        proposed_files = json.loads(response.text)
        
        # Guard against nested JSON like {"files": {"path": "..."}}
        if "files" in proposed_files and isinstance(proposed_files["files"], dict):
            proposed_files = proposed_files["files"]
            
    except Exception as e:
        print(f"Error during code generation: {e}")
        proposed_files = {}
        
    print(f"--> Generated modifications for: {list(proposed_files.keys())}")
    return {"proposed_files": proposed_files}


def verification_node(state: OrchestratorState) -> OrchestratorState:
    """Validates the generated code via AST/Syntax checks."""
    print("\n--- [Node: Verification] Linting and checking syntax ---")
    
    feedback = []
    passed = True
    proposed = state.get("proposed_files", {})
    
    if not proposed:
        passed = False
        feedback.append("Execution node returned no proposed files.")
        
    for path, code in proposed.items():
        if path.endswith(".py"):
            try:
                ast.parse(code)
            except SyntaxError as e:
                passed = False
                feedback.append(f"SyntaxError in {path} at line {e.lineno}: {e.msg}")
                
    retry_count = state.get("retry_count", 0) + 1
    feedback_str = "\n".join(feedback) if feedback else "Syntax check passed."
    
    print(f"--> Status: {'PASSED' if passed else 'FAILED'}. Retry Count: {retry_count}")
    if feedback:
        print(f"    Feedback: {feedback_str}")
        
    return {"verification_passed": passed, "verification_feedback": feedback_str, "retry_count": retry_count}


def commit_node(state: OrchestratorState) -> OrchestratorState:
    """Applies the code directly to the filesystem."""
    print("\n--- [Node: Commit] Applying changes ---")
    
    for path, code in state.get("proposed_files", {}).items():
        try:
            # Ensure directories exist
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(code)
            print(f"✅ Updated {path}")
        except Exception as e:
            print(f"❌ Failed to write {path}: {e}")
            
    return state


# ---------------------------------------------------------
# Edges
# ---------------------------------------------------------
def verification_router(state: OrchestratorState) -> str:
    if state.get("verification_passed"):
        return "commit_node"
    elif state.get("retry_count", 0) >= 3:
        print("\n❌ Max retries (3) reached. Failing out.")
        return END
    else:
        print("\n⚠️ Verification failed. Routing back to Execution Node for fixes...")
        return "execution_node"

# ---------------------------------------------------------
# Build Graph
# ---------------------------------------------------------
def build_graph():
    workflow = StateGraph(OrchestratorState)
    
    workflow.add_node("ingestion_node", ingestion_node)
    workflow.add_node("context_node", context_node)
    workflow.add_node("execution_node", execution_node)
    workflow.add_node("verification_node", verification_node)
    workflow.add_node("commit_node", commit_node)
    
    workflow.set_entry_point("ingestion_node")
    workflow.add_edge("ingestion_node", "context_node")
    workflow.add_edge("context_node", "execution_node")
    workflow.add_edge("execution_node", "verification_node")
    workflow.add_conditional_edges(
        "verification_node",
        verification_router,
        {
            "commit_node": "commit_node",
            "execution_node": "execution_node",
            END: END
        }
    )
    workflow.add_edge("commit_node", END)
    
    return workflow.compile()

if __name__ == "__main__":
    app = build_graph()
    
    # Test Run with Issue #1
    test_issue = {
        "issue_title": "Implement deterministic validation gates for agent database writes",
        "issue_body": "Currently, `backend/services/rag.py` takes raw `fc_args` from the LLM and blindly merges them into `workflow_state` and the `leads` table. We need a Pydantic validation layer before calling `db.table('conversations').update(...)` to prevent prompt injection or hallucinated schema parameters from corrupting the DB.",
        "issue_labels": ["backend", "security", "p1"],
        "retry_count": 0
    }
    
    print("===========================================")
    print("🚀 Wraft Orchestrator Loop Initialized")
    print("===========================================")
    
    for event in app.stream(test_issue):
        # The stream yields dicts after each node finishes
        pass 
    print("\n✅ Orchestrator Loop Complete!")
